name: timetracker
description: Papierkram.de - TimeTracker as flutter app
repository: https://github.com/SimonIT/timetracker.git

publish_to: 'none'

version: 1.5.5+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.5
  http: ^0.13.5
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^6.0.0
  json_annotation: ^4.7.0
  duration: ^3.0.12
  uuid: ^3.0.6
  flutter_typeahead: ^4.1.1
  easy_refresh: ^3.0.4+2
  html_unescape: ^2.0.0
  flutter_cupertino_settings: ^0.5.0
  url_launcher: ^6.1.6
  in_app_purchase: ^3.0.8
  app_review: ^2.1.2+1
  file_picker: ^5.2.2
  open_file:
    git:
      url: https://github.com/crazecoder/open_file.git
  flutter_cache_manager: ^3.3.0
  sentry_flutter: ^6.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.12
  build_runner: ^2.3.2
  json_serializable: ^6.5.4

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/icon_android.png"
  image_path_ios: "assets/images/icon_ios.png"
  adaptive_icon_background: "#B9D5DE"
  adaptive_icon_foreground: "assets/images/icon_android.png"

flutter_native_splash:
  image: "assets/images/icon_splash.png"
  color: "#B9D5DE"
