name: timetracker
description: Papierkram.de - TimeTracker as flutter app
repository: https://github.com/SimonIT/timetracker.git

publish_to: 'none'

version: 1.5.5+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.3
  http: ^0.13.3
  shared_preferences: ^2.0.8
  flutter_secure_storage: ^4.2.1
  json_annotation: ^4.1.0
  duration: ^3.0.6
  uuid: ^3.0.4
  flutter_typeahead: ^3.2.1
  flutter_easyrefresh: ^2.2.1
  html_unescape: ^2.0.0
  flutter_cupertino_settings: ^0.5.0
  url_launcher: ^6.0.11
  in_app_purchase: ^1.0.9
  app_review: ^2.1.1+1
  file_picker: ^4.1.0
  open_file: ^3.1.0
  flutter_cache_manager: ^3.1.2
  sentry_flutter: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.3
  build_runner: ^2.1.2
  json_serializable: ^5.0.1

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/icon_android.png"
  image_path_ios: "assets/images/icon_ios.png"
  adaptive_icon_background: "#B9D5DE"
  adaptive_icon_foreground: "assets/images/icon_android.png"

flutter_native_splash:
  image: "assets/images/icon_splash.png"
  color: "#B9D5DE"
